"""Nutrition verification agent backed by deterministic functions."""

from meal_agent.schemas import IngredientPortion, NutritionTarget, VerificationResult
from meal_agent.tools.nutrition import verify_macros


def verify_candidate(
    ingredients: list[IngredientPortion], target: NutritionTarget
) -> VerificationResult:
    """Verify a proposed meal; never trust macro totals generated by an LLM."""
    return verify_macros(ingredients, target)
